# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
to dependaBOT.install |LayerDevices On The SatelliteRinkAroundTheWorld Insert Workinplug TO SATELITES
LINK SATELLITE EACH AMND EVERY HONOR ANDROID DRONOR DONMORNDORORROMZOMMEMORYZONERONORHONORATITSTACKEYSSTAGELEVEL1
SPEEDDIALMODEMS INSTALLED ON THE NASA FLYINGOBJECTDEVICES AT SPACE THROUGHSPACENADARRADATRJ"RJESTELM"KESKUSNASAPENTAGONRADARSYSTEM 1
installed in start now
